name: survay_service

include:
  - docker/compose/app.yml
  - docker/compose/db.yml

networks:
  survay_service.network:
    name: survay_service.network

volumes:
  survay_service_postgres_data:
    name: survay_service_postgres_data
  survay_service_static_data:
    name: survay_service_static_data
