services:
  survay_redis:
    container_name: survay_service.redis
    hostname: survay_service.redis
    image: redis:latest
    command: redis-server --save 30 1 --appendonly yes
    restart: unless-stopped
    expose:
      - "${REDIS_PORT}"
    volumes:
      - survay_service_redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - survay_service.network
