# Generated by Django 6.0 on 2026-03-06 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.CharField(max_length=1000, verbose_name="текст вопроса"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Порядок должен быть >= 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                15, message="Порядок должен быть <= 15"
                            ),
                        ],
                        verbose_name="порядок",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="текст варианта"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Порядок должен быть >= 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message="Порядок должен быть <= 5"
                            ),
                        ],
                        verbose_name="порядок",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer_options",
                        to="survays.question",
                        verbose_name="вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "вариант ответа",
                "verbose_name_plural": "варианты ответов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Survay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="название опроса"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_survays",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "опрос",
                "verbose_name_plural": "опросы",
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="survay",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="survays.survay",
                verbose_name="опрос",
            ),
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="имя пользователя"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="время начала"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now=True, verbose_name="время ответа"),
                ),
                (
                    "answer_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_selections",
                        to="survays.answeroption",
                        verbose_name="выбранный вариант",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="survays.question",
                        verbose_name="вопрос",
                    ),
                ),
                (
                    "survay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_answers",
                        to="survays.survay",
                        verbose_name="опрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ пользователя",
                "verbose_name_plural": "ответы пользователей",
                "indexes": [
                    models.Index(
                        fields=["survay", "username"],
                        name="survays_use_survay__1986b6_idx",
                    ),
                    models.Index(
                        fields=["survay", "username", "question"],
                        name="survays_use_survay__bc14db_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("username", "question"), name="unique_user_question"
                    )
                ],
            },
        ),
    ]
